spring:
  application:
    name: MyFirstApplication
  config:
    import: optional:file:.env[.properties]
  datasource:        
    url: "jdbc:postgresql://${HOST_NAME}:5432/${DATABASE_NAME}"
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}